## Fancy indexing 

In [1]:
import numpy as np

In [37]:
arr2d = np.arange(36).reshape(4,9)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [15]:
arr2d[1: :2, [4,8,3,0,8]] #

array([[13, 17, 12,  9, 17],
       [31, 35, 30, 27, 35]])

In [9]:
arr2d[[3,1,2,0], [3,7,2,4]] # 
                            # 

array([30, 16, 20,  4])

In [12]:
arr2d[[1,1,1,1,1,3,3,3,2,2],[4,8,3,0,8,4,8,3,0,8]].reshape(2,5)

array([[13, 17, 12,  9, 17],
       [31, 35, 30, 18, 26]])

In [4]:
arr2d[:,[5,8,0,3]] # [19, 33, 14, 2] [:, 0:8:2]

array([[ 5,  8,  0,  3],
       [14, 17,  9, 12],
       [23, 26, 18, 21],
       [32, 35, 27, 30]])

In [7]:
np.array([[9,14,29, 25],
          []])

array([[ 9, 14, 29, 25]])

In [6]:
arr2d[[0,2,3],[2,7,8]] 

array([ 2, 25, 35])

In [6]:
arr2d[:,::3]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [7]:
arr2d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [22]:
arr2d[:,-1::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [3]:
arr3d = np.arange(80).reshape(4,4,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]]])

In [4]:
arr3d[1][1][2]

27

In [11]:
arr3d[3][1][3]

55

In [5]:
arr3d[2:3,1:2,1:4]

array([[[46, 47, 48]]])

In [6]:
arr3d[2][1][1:4]

array([46, 47, 48])

In [7]:
arr3d[3: ,1:3, 2:4]

array([[[67, 68],
        [72, 73]]])

In [9]:
arr3d[3][1:3][2:4]

array([], shape=(0, 5), dtype=int32)

In [13]:
arr3d[3:4,1:3,1:3]

array([[[53, 54],
        [57, 58]]])

In [14]:
arr3d[:,2:3,1:3]

array([[[ 9, 10]],

       [[25, 26]],

       [[41, 42]],

       [[57, 58]]])

In [15]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,4,5),dtype='float')

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [17]:
np.zeros((4,5),dtype='float')

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.ones((5,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [24]:
np.ones((3,5,2),dtype='int')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr2d1 = np.arange(12).reshape(3,4)
arr2d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
arr2d1 + 5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
arr2d1 -3

array([[-3, -2, -1,  0],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [17]:
arr2d1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [19]:
arr2d2 = np.arange(12,24).reshape(3,4)
arr2d2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
arr2d1 + arr2d2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [21]:
arr2d1 - arr2d2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [26]:
arr2d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr2d2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
arr2d2 * arr2d1

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [30]:
arr2d3 = np.arange(12,24).reshape(4,3)
arr2d3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [33]:
np.dot(arr2d3,arr2d2)

array([[ 632,  671,  710,  749],
       [ 776,  824,  872,  920],
       [ 920,  977, 1034, 1091],
       [1064, 1130, 1196, 1262]])

In [30]:
arr2d2 = np.random.randn(3,4)

In [31]:
arr2d1 + arr2d2

array([[ 0.13928366,  0.37908541,  3.05035917,  2.43777085],
       [ 5.88186518,  4.86550527,  7.15935856,  6.02064469],
       [ 6.87350478,  8.14274003,  9.63615885, 11.90981936]])

In [32]:
arr2d3 = np.random.randn(4,4)
arr2d3

array([[ 1.58367829,  1.0061472 ,  0.7397189 , -1.89713684],
       [ 1.59307853,  0.65701654, -1.38280591,  1.69088344],
       [ 0.94636043, -0.52589905, -0.0549804 ,  0.5823293 ],
       [ 0.16097976, -0.78684691,  1.22295258,  1.15259518]])

In [38]:
arr2d3 + arr2d2

ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [34]:
arr2d4 = np.ones((3,3))*2
arr2d4  

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [35]:
arr2d5 = np.ones((3,3))*3
arr2d5  

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [37]:
# mirror multiplicztion
arr2d5 * arr2d4

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [38]:
a = np.arange(6).reshape(3,2)
b = np.arange(6).reshape(2,3)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [39]:
a*b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [40]:
b*a

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [42]:
# Matrix Multiplication
# Column of first == Rows of second (Checking operation)
# Row of first * Column of second (Multiply operation)
a@b

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [43]:
b@a

array([[10, 13],
       [28, 40]])

In [44]:
c = np.arange(15).reshape(5,3)
d = np.arange(10).reshape(2,5)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [45]:
c@d

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [48]:
d@c

array([[ 90, 100, 110],
       [240, 275, 310]])

In [49]:
d.dot(c)

array([[ 90, 100, 110],
       [240, 275, 310]])

In [34]:
np.full((4,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [51]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [52]:
np.zeros_like(a)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [53]:
np.ones_like(a)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [39]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [57]:
arr2d > 5

array([[False, False, False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [44]:
(arr2d > 5).sum()

30

In [60]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [45]:
arr2d[arr2d %2 ==0] 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34])

In [46]:
arr2d[arr2d %2 ==0].sum()

306

In [62]:
arr2d[(arr2d >10)  &  (arr2d<30)]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [63]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [64]:
new3darray = arr3d.ravel()
new3darray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [65]:
arr3d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [66]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [67]:
arr3d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [68]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [69]:
arr3d.reshape(64)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])