# Import numpy library

In [1]:
import numpy as np

Convrting list to array

In [7]:
data = [1,2,3.4]
arr = np.array(data)
arr

array([1. , 2. , 3.4])

Converting Tuple to Array

In [9]:
tup=(1,2,3)
artup = np.array(tup)
artup

array([1, 2, 3])

In [10]:
artup.ndim

1

In [11]:
s={1,2,3,4}
setup = np.array(s)
setup

array({1, 2, 3, 4}, dtype=object)

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
array = np.array(data2)
array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
array.astype(float)


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [14]:
array.ndim

2

In [15]:
array.shape

(2, 4)

In [16]:
zero_array = np.zeros(7)
zero_array

array([0., 0., 0., 0., 0., 0., 0.])

In [17]:
z1 = np.zeros((3,5))

In [18]:
one = np.ones(5)
one

array([1., 1., 1., 1., 1.])

In [19]:
one2d = np.ones((2,4))
one2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
em = np.empty((1, 3, 2))
em

array([[[5.88242065e+25, 4.84886969e-23],
        [2.38296654e+06, 5.48271264e-86],
        [4.43352822e+25, 1.70658590e+93]]])

In [21]:
em1 = np.empty((2, 3, 2))
em1

array([[[9.49447596e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [9.34609789e-307, 1.58817677e-052]],

       [[4.46936566e-090, 3.50592775e-033],
        [9.99240349e-048, 3.73539840e-033],
        [3.99910963e+252, 9.76480236e+165]]])

In [22]:
n =np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
num = np.arange(2,15,3)
num

array([ 2,  5,  8, 11, 14])

In [24]:
num.dtype

dtype('int32')

In [25]:
l=['sd','ff']
a=np.array(l)
a.dtype

dtype('<U2')

In [26]:
sub = arr-artup
sub

array([0. , 0. , 0.4])

In [27]:
mul = arr*artup
mul

array([ 1. ,  4. , 10.2])

In [28]:
arr3d = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])
arr3d[1] = 42
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[42, 42, 42],
        [42, 42, 42]]])

In [42]:
print(arr3d[0][1][2])
# arr3d[0] = [1,2,3]
# arr3d

3


In [43]:
full = np.full((2,3), 5)
full

array([[5, 5, 5],
       [5, 5, 5]])

In [94]:
arthe = np.linspace(1,100,20)
arthe

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [48]:
random = np.random.random((3,3))
random

array([[0.89200988, 0.79480211, 0.87275994],
       [0.72697819, 0.76868177, 0.82013488],
       [0.50819449, 0.10958445, 0.68573694]])

In [91]:
random1 = np.random.rand(3,4)
random1

array([[0.86500973, 0.97075798, 0.33181341, 0.32332029],
       [0.02918256, 0.64305713, 0.29399689, 0.7795183 ],
       [0.36756415, 0.14076498, 0.94923028, 0.51558119]])

In [92]:
random2 = np.random.randn(3,4)
random2

array([[ 0.53372495,  1.5730541 , -0.37629345, -1.69841251],
       [ 0.28255847, -0.042837  , -0.03717329,  1.10861119],
       [ 0.41036212,  0.29827028, -0.78634087,  1.27639807]])

In [96]:
normal = np.random.normal(1, 10, (3, 3))
normal

array([[ -8.36497026,  -4.87100582,  -2.50959909],
       [-19.89299779,   0.60612195,  -4.72836313],
       [-11.63232857,  12.94142232,  -2.01228829]])

In [52]:
randint = np.random.randint(1,20,(3, 3))
randint

array([[ 9, 15, 12],
       [ 7,  2,  3],
       [ 2, 19, 10]])

In [57]:
identity = np.eye(2)
identity

array([[1., 0.],
       [0., 1.]])

In [153]:
x3 = np.random.randint(60, size=(3, 4, 5)) 
x3.reshape((1,60))


array([[37,  9,  2, 13, 26,  5,  8, 34, 59, 59, 21,  2, 27, 54, 15,  7,
        36, 55, 21, 44, 32, 54, 35, 36, 11, 43, 19,  1, 32, 30, 44, 52,
        59, 37, 38,  1, 54, 47, 18,  6, 18,  4, 18, 36, 57, 36, 58, 52,
        37, 53, 43, 28, 37, 33, 29, 58, 27, 57, 30, 45]])

In [59]:
print(x3.ndim)
print(x3.shape)
print(x3.size)

3
(3, 4, 5)
60


In [63]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [98]:
x2 = np.random.randint(50, size=(4, 5)) 
print(x2)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

[[44 39 16 47 29]
 [15  7 23 13 19]
 [41 48 27 28  9]
 [38 41  1 39 48]]
itemsize: 4 bytes
nbytes: 80 bytes


In [99]:
x2 = np.random.randint(50, size=(4, 5)) 
print(x2)

[[32 18 14 26 34]
 [21 45 32 14 32]
 [32 30 40 27  9]
 [11 38 17 42  9]]


In [130]:
x2[::-1, ::1]

array([[11, 38, 17, 42,  9],
       [32, 30, 40, 27,  9],
       [21, 45, 32, 14, 32],
       [32, 18, 14, 26, 34]])

In [125]:
x2[-1:-3:-1, :]

array([], shape=(0, 5), dtype=int32)

In [116]:
x2[:2,3]

array([26, 14])

In [70]:
x2[2,2]=12
x2

array([[ 8,  7,  6,  0,  4],
       [ 1,  9,  4,  0,  3],
       [ 4,  8, 12,  5,  9],
       [ 3,  7,  4,  4,  4]])

In [77]:
x2[::-1, ::-1]

array([[ 4,  4,  4,  7,  3],
       [ 9,  5, 12,  8,  4],
       [ 3,  0,  4,  9,  1],
       [ 4,  0,  6,  7,  8]])

In [78]:
x2[::-1, ::1]

array([[ 3,  7,  4,  4,  4],
       [ 4,  8, 12,  5,  9],
       [ 1,  9,  4,  0,  3],
       [ 8,  7,  6,  0,  4]])

In [69]:
x2[-3, -3]

4

In [71]:
x2

array([[ 8,  7,  6,  0,  4],
       [ 1,  9,  4,  0,  3],
       [ 4,  8, 12,  5,  9],
       [ 3,  7,  4,  4,  4]])

In [75]:
x2[1: :2, ::3]

array([[1, 0],
       [3, 4]])

In [76]:
x2[1: :2, 0:4:3]

array([[1, 0],
       [3, 4]])

In [72]:
x2[1:3, 2:]

array([[ 4,  0,  3],
       [12,  5,  9]])

In [73]:
x2[2: , 0:2]

array([[4, 8],
       [3, 7]])

In [74]:
x2[1:3, 0: :2]

array([[ 1,  4,  3],
       [ 4, 12,  9]])

In [157]:
grid = np.random.randint(10,size=(2,3))
grid

array([[5, 0, 1],
       [3, 9, 4]])

In [158]:
con = np.concatenate([grid, grid])
con

array([[5, 0, 1],
       [3, 9, 4],
       [5, 0, 1],
       [3, 9, 4]])

In [160]:
con1 = np.concatenate([grid, grid], axis=0) 
con1

array([[5, 0, 1],
       [3, 9, 4],
       [5, 0, 1],
       [3, 9, 4]])

In [63]:
data1 = np.random.rand(7, 4)
data1

array([[0.60851884, 0.03512343, 0.27276671, 0.49118397],
       [0.92809156, 0.8595083 , 0.88110192, 0.44356786],
       [0.31858845, 0.13900773, 0.72868662, 0.03349105],
       [0.72314363, 0.75758596, 0.24886158, 0.74289789],
       [0.75145586, 0.52002089, 0.65128321, 0.79398167],
       [0.66588907, 0.13305186, 0.52818167, 0.20451531],
       [0.33349426, 0.31250657, 0.14309179, 0.12621643]])

In [69]:
d2 =  np.random.random((3, 3))
d2

array([[0.52593265, 0.87755013, 0.28725864],
       [0.70047111, 0.56377503, 0.47888493],
       [0.69885729, 0.51076272, 0.22347456]])

In [65]:
data1[data1<0.4]=0
data1

array([[0.60851884, 0.        , 0.        , 0.49118397],
       [0.92809156, 0.8595083 , 0.88110192, 0.44356786],
       [0.        , 0.        , 0.72868662, 0.        ],
       [0.72314363, 0.75758596, 0.        , 0.74289789],
       [0.75145586, 0.52002089, 0.65128321, 0.79398167],
       [0.66588907, 0.        , 0.52818167, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [66]:
full = np.full((3, 5), 3.14)
full

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [68]:
line = np.linspace(0, 10, 5)
line

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
t=(2,4,1)
sorted(t, reverse=True)

[4, 2, 1]

In [9]:
sum = 3+4

In [10]:
print(sum)

7


In [20]:
num1 =input("Enter any number")

Enter any numberwerdf


In [17]:
num2 = input("Enter 2nd number")

Enter 2nd number23


In [12]:
sm = num1 + num2 
sub = num1 - num2 
mul = num1 * num2 
div = num1 / num2 
power = num1 ** num2 

In [13]:
print(power)

64


In [21]:
print(sub)
print('the subtraction is')

1
the subtraction is


In [23]:
name = "Alice"
age  = 22

In [24]:
print('your name is ', name, ' your age is ', age)

your name is  Alice  your age is  22


In [25]:
print(f"your name is {name} your age is {age}")

your name is Alice your age is 22


In [26]:
name

'Alice'

In [2]:
s = 'Hello! my name is Alive 2'

In [3]:
s.isalpha()

False

In [4]:
q = 'adakd'
q.isalpha()

True

In [5]:
s.isspace()

False

In [6]:
s.islower()

False

In [7]:
q.islower()

True

In [10]:
r = '123'
r.isdigit()
# r.isnum()

True