# Learning Numpy 

## Numpy - Numerical Python 
      - structure - Numpy ndimensional 
      - Super fast processing
      - it deals only in numeric values

### Creating a numpy Array 

Dimensional Array

In [2]:
import numpy as np

In [3]:
# using python list
lst = [1,2,3,4,5,6,7,8,9,10]
print(type(lst))
arr1d = np.array(lst)
type(arr1d)

<class 'list'>


numpy.ndarray

In [4]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
lst * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Vectorized Operation
 

In [6]:
arr1d * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr1d/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [8]:
arr1d +2 

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
arr1d - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [10]:
arr1d % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [11]:
arr1d.size

10

In [12]:
arr1d.ndim

1

In [13]:
arr1d.shape

(10,)

In [14]:
#Using numpy arange
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#2dArray from python list
lst2d = [[1,2,3],[11,22,33],[111,222,333]]
lst2d

[[1, 2, 3], [11, 22, 33], [111, 222, 333]]

In [16]:
arr2d = np.array(lst2d)
arr2d

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [17]:
arr2d.ndim

2

In [18]:
arr2d.shape

(3, 3)

In [19]:
arr2d = np.arange(36).reshape(4,9)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [20]:
arr2d = np.arange(36).reshape(9,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [21]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr1d[7]

7

In [23]:
arr1d[4:8]

array([4, 5, 6, 7])

In [24]:
arr1d[-1]

9

In [25]:
arr1d[5]

5

In [26]:
arr1d[5:6]

array([5])

In [27]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [28]:
arr2d.reshape(4,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [29]:
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [30]:
arr2d = arr2d.reshape(4,9)

In [31]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [32]:
# index value 23 from arr2d
arr2d[2][5]

23

In [33]:
arr2d[2,5]

23

In [34]:
# arr2d[row,col]  >>> [startrow:endrow,statcol:endcol]

arr2d[1:2,2:7]
#Slice

array([[11, 12, 13, 14, 15]])

In [35]:
arr2d[1:3,5:7]

array([[14, 15],
       [23, 24]])

In [36]:
arr2d[0:4, 6:9]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [37]:
arr2d[:, 6:].shape

(4, 3)

In [38]:
arr2d[2,4:7]


array([22, 23, 24])

In [39]:
arr2d[:,-1]

array([ 8, 17, 26, 35])

In [40]:
arr2d[:,8:]

array([[ 8],
       [17],
       [26],
       [35]])

In [41]:
arr2d[:,::3]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [42]:
arr2d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
type(np.arange(10))

numpy.ndarray

In [45]:
np.arange(10).ndim

1

In [46]:
np.arange(10).shape

(10,)

In [47]:
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [48]:
type(np.arange(10).reshape(1,10))

numpy.ndarray

In [49]:
np.arange(10).reshape(1,10).ndim

2

In [50]:
np.arange(10).reshape(1,10).shape

(1, 10)

In [51]:
np.array([[19]])

array([[19]])

In [52]:
np.array([[19,1, 2], [4, 5, 6]])

array([[19,  1,  2],
       [ 4,  5,  6]])

In [53]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [54]:
# Fancy Indexing
arr2d[[0,2],[2,7]]


array([ 2, 25])

In [55]:
arr3d = np.arange(64).reshape(4,4,4)

In [56]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [57]:
arr3d[1][2][2]

26

In [58]:
arr3d[3][1][3]

55

In [59]:
arr3d[2:3, :3, :3]

array([[[32, 33, 34],
        [36, 37, 38],
        [40, 41, 42]]])

In [79]:
arr3d[2:3, :3, :3]

array([[[32, 33, 34],
        [36, 37, 38],
        [40, 41, 42]]])

In [61]:
arr3d[2:3, :3, 0]

array([[32, 36, 40]])

In [62]:
arr3d[2:3, :3, 0].shape

(1, 3)

In [63]:
arr3d[3:4,1:3,1:3]

array([[[53, 54],
        [57, 58]]])

In [64]:
arr3d[:,2:3,1:3]

array([[[ 9, 10]],

       [[25, 26]],

       [[41, 42]],

       [[57, 58]]])

In [65]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
type(np.zeros(12))

numpy.ndarray

In [67]:
type(np.zeros(12)[0])

numpy.float64

In [68]:
np.zeros((4,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [69]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [70]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
np.ones((5,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [72]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
arr2d1 = np.arange(12).reshape(3,4)
arr2d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
arr2d1 = np.arange(12,24).reshape(3,4)

In [75]:
arr2d1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
arr2d2 = np.random.randn(3,4)

In [77]:
arr2d2

array([[ 0.18519963,  0.62329385,  0.11007525, -0.24346543],
       [ 0.39557184, -0.51908154, -0.62253059,  0.59551076],
       [-0.41608262,  0.7347886 ,  1.26474482, -0.21640973]])

In [78]:
arr2d1 + arr2d2

array([[12.18519963, 13.62329385, 14.11007525, 14.75653457],
       [16.39557184, 16.48091846, 17.37746941, 19.59551076],
       [19.58391738, 21.7347886 , 23.26474482, 22.78359027]])